#!/usr/bin/env escript

main(_) ->
  Name = env("BEAMUP_PROJECT_NAME"),
  Url = env("BEAMUP_STORE_URL"),
  Secret = env("BEAMUP_STORE_SECRET"),
  Path = <<"/host/project/", Name/binary>>,
  beamup:run(Path, Url, Secret).

env(Key) ->
  case os:getenv(Key) of
    false -> throw("Please set environment variable " ++ Key);
    Val -> list_to_binary(Val)
  end.
