#!/usr/bin/env escript

main(_) ->
  Url = env("BEAMUP_STORE"),
  Secret = env("BEAMUP_STORE_SECRET"),
  Branch = env("BEAMUP_NODE_BRANCH"),
  beamup:node(Branch, Url, Secret).

env(Key) ->
  case os:getenv(Key) of
    [_|_] = Val -> list_to_binary(Val);
    _ -> <<>>
  end.
