#!/bin/bash

set -e

cli_args="${@}"
cwd=$(pwd)
templates_dir=$(dirname "$(readlink -f "$0")")

export BEAMUP_PROJECT_NAME="$1"
project_dir="$cwd/$BEAMUP_PROJECT_NAME"
template="erlang"

fail () {
  echo "Failed to create project: $1"
  exit 1
}

# Copy template to new project folder
mkdir "$BEAMUP_PROJECT_NAME" || fail "Directory already exists"
cp -R "$templates_dir/$template/." "$project_dir/"
cd $BEAMUP_PROJECT_NAME

# Replace `beamup_project_name` placeholder with $BEAMUP_PROJECT_NAME
replace_pattern="s/beamup_project_name/$BEAMUP_PROJECT_NAME/"


# replace in file contents
perl -pi -w -e "$replace_pattern;" $( grep -rl "beamup_project_name" . )

# rename directories depth-first
find "$project_dir" -depth -type d -exec $templates_dir/rename_dir '{}' \;

# rename files
find "$project_dir" -type f -exec $templates_dir/rename_file '{}' \;

git init
git add .
git commit -m 'Initial commit'

echo ""
echo "Yay! Your $project project '$BEAMUP_PROJECT_NAME' is ready:"
echo "  $project_dir"
echo ""
echo "  Run:"
echo "  $  cd ./$BEAMUP_PROJECT_NAME"
